### ISSUE TITLE
Support v1alpha2

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#127]
/kind feature

**Describe the solution you'd like**
This is a tracking issue for getting CAPD to support v1alpha2

- [ ] #123 Update capdctl to support v1a2 infrastructure 
- [x] #125 Import the new types and stop importing the old types
- [x] #67 Implement a release strategy for v1a1
- [ ] #131 Update documentation
- [ ] Add more here

**Anything else you would like to add:**
/cc @fabianofranz
